# Generated by Django 5.2 on 2025-05-07 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(max_length=100)),
                ('anos_experiencia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('genero', models.CharField(max_length=10)),
                ('grupo_sanguineo', models.CharField(max_length=10)),
                ('historia_clinica', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctoresEspecialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctores')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.especialidades')),
            ],
        ),
        migrations.AddField(
            model_name='doctores',
            name='doctores_especialidades',
            field=models.ManyToManyField(through='api.DoctoresEspecialidades', to='api.especialidades'),
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('motivo_consulta', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctores')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pacientes')),
            ],
        ),
    ]
